DELIMITER //
CREATE FUNCTION calculate_gpa(p_student_id INT)
RETURNS DECIMAL(3,2)
DETERMINISTIC READS SQL DATA
BEGIN
  RETURN IFNULL((SELECT ROUND(AVG(CASE WHEN Grade='A+' THEN 4.0 WHEN Grade='A' THEN 4.0 WHEN Grade='B+' THEN 3.5 WHEN Grade='B' THEN 3.0 WHEN Grade='C+' THEN 2.5 WHEN Grade='C' THEN 2.0 WHEN Grade='D' THEN 1.0 ELSE 0 END), 2) FROM ATTEMPTS WHERE StudentID = p_student_id AND Grade IS NOT NULL), 0);
END //


CREATE FUNCTION count_enrollments(p_offering_id INT)
RETURNS INT
DETERMINISTIC READS SQL DATA
RETURN IFNULL((SELECT COUNT(*) FROM ENROLLMENT WHERE OfferingID = p_offering_id AND Status='Active'), 0) //
DELIMITER ;
