CREATE TABLE PERSON (
    PersonID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    DOB DATE NOT NULL
);

CREATE TABLE PERSON_PHONE (
    PersonID INT NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    PRIMARY KEY (PersonID, PhoneNumber),
    FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE DEPARTMENT (
    DepartmentID INT PRIMARY KEY AUTO_INCREMENT,
    DepartmentName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROGRAM (
    ProgramID INT PRIMARY KEY AUTO_INCREMENT,
    ProgramName VARCHAR(100) NOT NULL,
    Level VARCHAR(50) NOT NULL,
    DurationYears INT NOT NULL,
    DepartmentID INT NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID) ON DELETE RESTRICT,
    UNIQUE KEY (ProgramName, DepartmentID),
    CHECK (DurationYears BETWEEN 1 AND 6)
);

CREATE TABLE STUDENT (
    PersonID INT PRIMARY KEY,
    RollNo VARCHAR(20) NOT NULL UNIQUE,
    AdmissionYear INT NOT NULL,
    ProgramID INT NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (ProgramID) REFERENCES PROGRAM(ProgramID) ON DELETE RESTRICT
);

CREATE TABLE FACULTY (
    PersonID INT PRIMARY KEY,
    EmployeeCode VARCHAR(20) NOT NULL UNIQUE,
    Designation VARCHAR(50) NOT NULL,
    DepartmentID INT NOT NULL,
    FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID) ON DELETE RESTRICT
);


CREATE TABLE COURSE (
    CourseID INT PRIMARY KEY AUTO_INCREMENT,
    CourseTitle VARCHAR(100) NOT NULL,
    Credits INT NOT NULL,
    ProgramID INT NOT NULL,
    FOREIGN KEY (ProgramID) REFERENCES PROGRAM(ProgramID) ON DELETE RESTRICT,
    CHECK (Credits BETWEEN 1 AND 6),
    UNIQUE KEY (CourseTitle, ProgramID)
);

CREATE TABLE THEORY_COURSE (
    CourseID INT PRIMARY KEY,
    LectureHours INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID) ON DELETE CASCADE,
    CHECK (LectureHours > 0)
);

CREATE TABLE LAB_COURSE (
    CourseID INT PRIMARY KEY,
    LabHours INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID) ON DELETE CASCADE,
    CHECK (LabHours > 0)
);

CREATE TABLE SEMESTER (
    SemesterID INT PRIMARY KEY AUTO_INCREMENT,
    SemesterName VARCHAR(50) NOT NULL UNIQUE,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CHECK (EndDate > StartDate)
);

CREATE TABLE COURSE_OFFERING (
    OfferingID INT PRIMARY KEY AUTO_INCREMENT,
    CourseID INT NOT NULL,
    SemesterID INT NOT NULL,
    Section VARCHAR(5) NOT NULL,
    MaxSeats INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID) ON DELETE RESTRICT,
    FOREIGN KEY (SemesterID) REFERENCES SEMESTER(SemesterID) ON DELETE RESTRICT,
    CHECK (MaxSeats > 0),
    UNIQUE KEY (CourseID, SemesterID, Section)
);


CREATE TABLE ENROLLMENT (
    StudentID INT NOT NULL,
    OfferingID INT NOT NULL,
    EnrollmentDate DATE NOT NULL,
    Status ENUM('Active', 'Completed', 'Dropped', 'Inactive') NOT NULL,
    PRIMARY KEY (StudentID, OfferingID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (OfferingID) REFERENCES COURSE_OFFERING(OfferingID) ON DELETE CASCADE
);

CREATE TABLE TEACHING_ASSIGNMENT (
    FacultyID INT NOT NULL,
    OfferingID INT NOT NULL,
    Role ENUM('Instructor', 'Teaching Assistant', 'Lab Assistant') NOT NULL,
    AssignedHours INT NOT NULL,
    PRIMARY KEY (FacultyID, OfferingID),
    FOREIGN KEY (FacultyID) REFERENCES FACULTY(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (OfferingID) REFERENCES COURSE_OFFERING(OfferingID) ON DELETE CASCADE,
    CHECK (AssignedHours > 0)
);


CREATE TABLE ASSESSMENT (
    AssessmentID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100) NOT NULL,
    OfferingID INT NOT NULL,
    FOREIGN KEY (OfferingID) REFERENCES COURSE_OFFERING(OfferingID) ON DELETE CASCADE,
    UNIQUE KEY (Title, OfferingID)
);

CREATE TABLE QUIZ (
    AssessmentID INT PRIMARY KEY,
    FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID) ON DELETE CASCADE
);

CREATE TABLE ASSIGNMENT (
    AssessmentID INT PRIMARY KEY,
    FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID) ON DELETE CASCADE
);

CREATE TABLE EXAM (
    AssessmentID INT PRIMARY KEY,
    FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID) ON DELETE CASCADE
);

CREATE TABLE ASSESSMENT_ITEM (
    AssessmentID INT NOT NULL,
    ItemName VARCHAR(100) NOT NULL,
    MaxMarks INT NOT NULL,
    Weightage DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (AssessmentID, ItemName),
    FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID) ON DELETE CASCADE,
    CHECK (MaxMarks > 0 AND Weightage > 0 AND Weightage <= 100)
);

CREATE TABLE ATTEMPTS (
    StudentID INT NOT NULL,
    AssessmentID INT NOT NULL,
    MarksObtained INT NOT NULL,
    Grade ENUM('A+', 'A', 'B+', 'B', 'C+', 'C', 'D', 'F'),
    PRIMARY KEY (StudentID, AssessmentID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(PersonID) ON DELETE CASCADE,
    FOREIGN KEY (AssessmentID) REFERENCES ASSESSMENT(AssessmentID) ON DELETE CASCADE,
    CHECK (MarksObtained >= 0)
);



