DELIMITER //

CREATE TRIGGER prevent_enrollment_if_full
BEFORE INSERT ON ENROLLMENT
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM ENROLLMENT WHERE OfferingID = NEW.OfferingID) >=
     (SELECT MaxSeats FROM COURSE_OFFERING WHERE OfferingID = NEW.OfferingID) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Course full';
  END IF;
END //

CREATE TRIGGER prevent_duplicate_enrollment
BEFORE INSERT ON ENROLLMENT
FOR EACH ROW
BEGIN
  IF EXISTS (SELECT 1 FROM ENROLLMENT WHERE StudentID = NEW.StudentID AND OfferingID = NEW.OfferingID) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Student already enrolled in this course';
  END IF;
END //

DELIMITER ;